### ISSUE TITLE
[GLSL_NV_ray_tracing] GLSL `mat3x4` version of `gl_ObjectToWorldNV` and `gl_WorldToObjectNV`?

### ISSUE THREAD

**Issue by helixd-2k18** [KhronosGroup/GLSL#104]
As I know, DirectX 12 with DXR using `mat3x4` (default), but have `mat4x3` version. But should GLSL's `GLSL_NV_ray_tracing` use `mat3x4` version of `gl_ObjectToWorldNV` and `gl_ObjectToWorldNV`? Or needs add some qualifiers, such as `row_major` and `column_major`?

**Comment by dgkoch** [comment]
Agreed we should add this to the standardized GLSL extension.  We don't plan to make any changes to the NV extension, as it's simple enough for the application to just transpose it.

**Comment by dgkoch** [comment]
This is included in GLSL_EXT_ray_tracing extension (see #114)
