### ISSUE TITLE
GLSL_NV_fragment_shader_barycentric.txt uses cp1252 encoding

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/GLSL#106]
File `extensions/nv/GLSL_NV_fragment_shader_barycentric.txt` cannot be parsed without knowing the encoding due to byte 0x93 for example.

Fix proposal in #105

**Comment by johnkslang** [comment]
Merged.

FYI, if you put "Fix #106..." in the commit comment, the issue would automatically close when the PR is merged.
