### ISSUE TITLE
Shader interface clarification in GLSL spec

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/GLSL#115]
Hey,
GLSL 4.60 defines a shader interface as:

> A shader interface is defined to be one of these:
> • All the uniform variables and uniform blocks declared in a program. This spans all compilation
> units linked together within one program.
> • All the buffer blocks declared in a program.
> • The boundary between adjacent programmable pipeline stages: This spans all the outputs
> declared in all compilation units of the first stage and all the inputs declared in all compilation
> units of the second stage. Note that for the purposes of this definition, the fragment shader and
> the preceding shader are considered to have a shared boundary even though in practice, all
> values passed to the fragment shader first pass through the rasterizer and interpolator.
> 

This reads to me to mean that buffer blocks and uniform blocks should be treated as different shader interfaces. Specifically, in the case of block naming, they would have different namespaces:

> A block name is allowed to have different definitions in different shader interfaces
> within the same shader, allowing, for example, an input block and output block to have the same
> name.

Discussions with @johnkslang in this pull request for the reference compiler:
https://github.com/KhronosGroup/glslang/pull/2156

Determined that for block naming, the buffer blocks and uniform blocks should share the same namespace. This matches what the current Intel and Nvidia GLSL compilers do as well. I think the spec should be clarified to match what the reference compiler (and other compilers) is doing.
Thanks!

**Comment by johnkslang** [comment]
I think it is reasonable to consider that there are three interfaces in a shader, not four:

1. inputs
2. outputs
3. uniform, including UBO and SSBO

We could make it work with four, but I'm unclear that's how most people are thinking or implementing to.

I guess the question is, who thinks there should be four?  Is it okay to have three?

**Comment by mbechard** [comment]
It's certainly more intuitive to me that there are 3. That's what I originally expected. I don't see UBO and SSBOs being different enough to warrant separation.

**Comment by johnkslang** [comment]
Khronos discussed this internally, and it turns out there is a mix of implementation's interpretations.  So, in the face of that, it was decided to leave the specification as is.  (We can regroup on the original issue back at the glslang repo.)
