### ISSUE TITLE
4.60 revision changes and discard with prior image load/store or SSBO operations

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/GLSL#118]
GLSL 4.60 revision 3 states the following about the discard keyword:

> The `discard` keyword is only allowed within fragment shaders. It can be used within a fragment shader to abandon the operation on the current fragment. This keyword causes the fragment to be discarded and no updates to any buffers will occur. Control flow exits the shader, and subsequent implicit or explicit derivatives are undefined when this exit is non-uniform.

Revision 5 has this wording, with emphasis on an added sentence:

> The `discard` keyword is only allowed within fragment shaders. It can be used within a fragment
shader to abandon the operation on the current fragment. This keyword causes the fragment to be
discarded and no updates to any buffers will occur. **Any prior writes to other buffers such as shader storage buffers are unaffected.** Control flow exits the shader, and subsequent implicit or explicit derivatives are undefined when this control flow is non-uniform

That sentence is kind of important. And it just kind of appeared in the specification, with nothing written into a "changes" line or anything.

Furthermore, GLSL ES 3.10 seems to have had this sentence too (I don't have easy access to any of its older revisions).

So the question here is... what is the intent? Was this change a bug-fix, and therefore we should act as if it was always there (and assume that implementations complied with the original intent)? The fact that ES seems to have always had this wording suggests that this is the case. Or was this a deliberate change for 4.60, which we should not assume applies to earlier versions?

**Comment by johnkslang** [comment]
I see this in the 3.10 specification but not in 3.00, probably considered as part of the addition of SSBOs.  It was then introduced into the desktop 4.60 rev. 5 when the ES and desktop specifications were merged for into a single ascii-doctor source.

The opposite of what it says really could not be done: while a shader is running, it is updating externally visible buffers and it would be unworkable to say those updates were somehow no longer present after a later **discard** was seen.

Is there concern with writes that may have started but not yet completed?  That seems a grey area in general given the lack of a clearer memory model and formalization of race conditions.  Ignoring that, I think the added sentence doesn't say much that had to be true anyway.
