### ISSUE TITLE
Question about interaction between explicit locations and xfb output

### ISSUE THREAD

**Issue by werman** [KhronosGroup/GLSL#121]
There is a bug in Mesa which messes up xfb output if there is explicit location specified for arrays/matrices, which raised a question whether explicit location has any effect on xfb output. Having read the spec - there is no interaction between them, however we want to make sure we understand it correctly.

My understanding is that xfb output is packed as tight as alignment rules permit. Per GLSL 4.60, "Transform Feedback Layout Qualifiers":

> Variables and block members qualified with xfb_offset can be scalars, vectors, matrices, structures, and (sized) arrays of these. The offset must be a multiple of the size of the first component of the first qualified variable or block member, or a compile-time error results. Further, if applied to an aggregate containing a double, the offset must also be  a multiple of 8, and the space taken in the buffer will be a multiple of 8. The given offset applies to the first component of the first member of the qualified entity. Then, within the  qualified entity, subsequent components are each assigned, in order, to the next available offset aligned to a multiple of that component’s size. Aggregate types are flattened down to the component level to get this sequence of components. It is a compile-time error to apply xfb_offset to the declaration of an unsized array.

So the xfb output with and without location specifier should be the same in all cases. Here are the examples I have in mind:

### 1)

```
layout(location = 0, xfb_buffer = 0, xfb_offset = 0) 
out float[2] a;
```

Varyings layout will be:

slot | 32b | 32b | 32b | 32b
-----|-----|-----|-----|-----
 0  | a[0] | - | - |  -
 1  |  a[1]  |  -  |  -  |  - 

XFB output:

 32b | 32b 
-----|-----
 a[0] | a[1]

### 2)

```
layout(location = 0, xfb_buffer = 0, xfb_offset = 0)
out dvec3[2] a;
```

Varyings:
slot | 32b | 32b | 32b | 32b
-----|-----|-----|-----|-----
 0  | a[0].x | a[0].x | a[0].y |  a[0].y
 1  |  a[0].z  |  a[0].z  |  -  |  - 
 2  | a[1].x | a[1].x | a[1].y |  a[1].y
 3  |  a[1].z  |  a[1].z  |  -  |  - 

XFB:

 32b | 32b | 32b | 32b | 32b | 32b | 32b | 32b | 32b | 32b | 32b | 32b
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
a[0].x | a[0].x | a[0].y |  a[0].y | a[0].z  |  a[0].z | a[1].x | a[1].x | a[1].y |  a[1].y|  a[1].z  |  a[1].z

### 3)

```
struct S {
   float a;
   double b;
};

layout(location = 0, xfb_buffer = 0, xfb_offset = 0) 
out S s;
```
Varyings:
slot | 32b | 32b | 32b | 32b
-----|-----|-----|-----|-----
 0  | a | - | - | -
 1  | b | b | - | -

XFB: 

 32b | 32b |  32b | 32b 
-----|-----|-----|-----
 a | - | b | b

Is this a correct interpretation?

Also looking through the spec I think that "Transform Feedback Layout Qualifiers" section of GLSL spec lacks examples with 64bit types.

**Comment by johnkslang** [comment]
> So the xfb output with and without location specifier should be the same in all cases.

Yes, I believe so.

I also agree that XFB packing is reasonable tight, yet still aligned, as you indicate, but will let IHVs confirm.

**Comment by pdaniell-nv** [comment]
Yeah, that sounds right to me. Closing.
