### ISSUE TITLE
can i use 'GL_EXT_debug_printf' in vulkan .comp files?

### ISSUE THREAD

**Issue by corleonechensiyu** [KhronosGroup/GLSL#122]
for example in xxx.comp file.
`#version 450
#extension GL_EXT_debug_printf : require
void main()
{
    debugPrintfEXT("hello /n");
}`

**Comment by johnkslang** [comment]
Probably, with another newline and the right Vulkan drivers, layers, and set up.

**Comment by corleonechensiyu** [comment]
@johnkslang thank you！

**Comment by johnkslang** [comment]
Real thanks go to others, like @jeffbolznv and generally driver writers, testers, and layer providers.
