### ISSUE TITLE
Mixed up descriptions for rayQueryGetIntersectionObjectRayDirectionEXT and rayQueryGetIntersectionObjectRayOriginEXT in GLSL_EXT_ray_query

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/GLSL#143]
The descriptions for [rayQueryGetIntersectionObjectRayDirectionEXT ](https://github.com/KhronosGroup/GLSL/blob/8081e1c587fbff9abf865e5d73accc1b3c6f8bc7/extensions/ext/GLSL_EXT_ray_query.txt#L416) and [rayQueryGetIntersectionObjectRayOriginEXT](https://github.com/KhronosGroup/GLSL/blob/8081e1c587fbff9abf865e5d73accc1b3c6f8bc7/extensions/ext/GLSL_EXT_ray_query.txt#L426)  don't match and seem to be mixed up:

        vec3 rayQueryGetIntersectionObjectRayDirectionEXT(rayQueryEXT q, bool committed);

    Returns object-space origin of ray for current intersection

        vec3 rayQueryGetIntersectionObjectRayOriginEXT(rayQueryEXT q, bool committed);

    Returns object-space direction of ray for current intersection.

**Comment by dgkoch** [comment]
Thanks for the report!

See #145 for fix.
