### ISSUE TITLE
Can gl_in be redeclared with an implicit array size in tessellation shaders?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/GLSL#15]
From https://github.com/KhronosGroup/glslang/issues/1300:

- Generally, an array declared as explicitly-sized cannot be redeclared without a size
- Tessellation evaluation and control shaders pre-declare `gl_in` as `gl_in[gl_MaxPatchVertices]`
- A later example of redeclaring `gl_in` uses `gl_in[]`, which seems okay for geometry shading, but not for tessellation

Now, the purpose of redeclaring a built-in block is to subset its members, not establish array size. So, it could be tolerated to redeclare `gl_in[]` even if it was pre-declared with a specific size.

Or, we could be firm that it needs a size, and must be redeclared as `gl_in[gl_MaxPatchVertices]`.

One question is how have drivers interpreted the specification? As, I think, the specification could be clarified in either direction.  We would then ensure glslang follows suit.

Another question is whether another part of the specification already makes this more clear.

(Currently, glslang is narrow, requiring the explicit redeclaration, which seems quite intentional, as the check is specific to built-in block redeclarations.)

**Comment by infapi00** [comment]
> One question is how have drivers interpreted the specification? As, I think, the specification could be clarified in either direction. We would then ensure glslang follows suit.

FWIW, this also applies to Mesa driver, and the piglit test suite. Right now mesa doesn't raise an error in such case, for example with the following piglit test:
generated_tests/spec/arb_tessellation_shader/execution/tes-input/tes-input-gl_ClipDistance.shader_test

depending on the conclusion of this, Mesa and piglit could need to be updated.

**Comment by pdaniell-nv** [comment]
For both GLSL and ESSL NVIDIA supports redeclaration of gl_in[] in tessellation shaders without an explicit size. It reuses the previously declared size, which if not previously declared is implicitly gl_MaxPatchVertices.

**Comment by janharaldfredriksen-arm** [comment]
Arm does the same as NVIDIA.

**Comment by linqunzju** [comment]
AMD does the same as NVIDIA.

**Comment by jackohound** [comment]
Qualcomm does the same as NVidia.

**Comment by johnkslang** [comment]
This agreement is now reflected in glslang.

**Comment by johnkslang** [comment]
Specification language is changed, internally to Khronos, and will be visible on next released update to GLSL.
