### ISSUE TITLE
Add sampler3DShadow support

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/GLSL#153]
Extending depth texture tests in CTS I noticed that we do not have `sampler3DShadow`, though Vulkan (and it SPIR-V) allows it.

We have support in GLSL for almost all depth texture types (`sampler2DShadow`, `samplerCubeShadow`, `sampler2DArrayShadow`, `sampler1DShadow`, `sampler1DArrayShadow`, and `samplerCubeArrayShadow`). May be it's worthy to extend GLSL with support of `sampler3DShadow`?

Also appropriate overloads for functions like `texture()` will be required.

Internal vk-gl-cts issue 2521.

**Comment by gnl21** [comment]
Vulkan has clarified that this is not allowed, so there's no need for GLSL support.
