### ISSUE TITLE
[Question] Fragment shader producing unexpected results

### ISSUE THREAD

**Issue by perrymacmurray** [KhronosGroup/GLSL#165]
Sorry for the undescriptive title, but I really don't know how to describe what's going on here.

I'm currently using LibGDX and am trying to render shadows. I have everything working now, mostly based off of [this guide](https://www.microbasic.net/tutorials/shadow-mapping/Full.html), but when I try and render too many objects at once the shader breaks.

Here are the scene vertex and fragment shaders I'm using:
[Vertex shader](https://github.com/ihmcrobotics/ihmc-open-robotics-software/blob/feature/shadows/ihmc-graphics/src/libgdx/resources/us/ihmc/gdx/shadows/scene_v.glsl)
[Fragment shader](https://github.com/ihmcrobotics/ihmc-open-robotics-software/blob/feature/shadows/ihmc-graphics/src/libgdx/resources/us/ihmc/gdx/shadows/scene_f.glsl)
Additionally, other files dealing with shadows can mostly be found [here](https://github.com/ihmcrobotics/ihmc-open-robotics-software/tree/feature/shadows/ihmc-graphics/src/libgdx/java/us/ihmc/gdx/lighting)

When I'm only rendering a few objects, the shader works as expected (the yellow balls indicate the positions of the lights)
![image](https://user-images.githubusercontent.com/20259300/127716430-b0fce305-528b-4de9-857c-a547567c6601.png)

However, when I try and render too much, this happens
https://imgur.com/a/C7VzJzC

Additionally, while trying to pinpoint the problem, I discovered that under some circumstances random textures from the graphics card can be rendered instead of the shadow
![image](https://user-images.githubusercontent.com/20259300/127716463-abb90b44-e3ec-4ed6-b8bb-e8f64c92a359.png)
This leads me to believe that the problem may be related to/caused by a problem with random memory access, but I have no idea where that would be coming from.

I was able to cause the weird texture problem by replacing a snippet of code in the fragment shader:

    gl_FragColor = finalColor;

with

    if (finalColor.r == color.a) {
        color.r = color.a;
    }

    gl_FragColor = color;

Without the if statement, it just shows the shadow map instead of the normal colors. However, adding the if statement (and forcing it to evaluate finalColor, I think otherwise it optimizes it out of the code) causes the problem.

**Comment by pdaniell-nv** [comment]
A better place to ask questions like this would be here: https://community.khronos.org/. I don't have any brilliant ideas. Perhaps depth testing is enabled when you do the shadow phase, and it should be disabled.
