### ISSUE TITLE
GLSL Specification 4.60.7: typos in function signatures

### ISSUE THREAD

**Issue by kociap** [KhronosGroup/GLSL#173]
In The OpenGL Shading Language, Version 4.60.7, [section 8.9.2. Texel Lookup Functions](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.html#texel-lookup-functions) the parameter `P` is missing a type in the `gsampler3D` overload of `textureGrad`
```
gvec4 textureGrad(gsampler3D sampler, P, vec3 dPdx, vec3 dPdy)
                                      ~ missing parameter type 'vec3'
```

In [section 8.12, Image Functions](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.html#image-functions) one of the overloads of `imageSize` is listed with the type `gimageRect` which does not exist. The correct parameter type should be `gimage2DRect`
```
ivec2 imageSize(readonly writeonly gimageRect image)
                                   ~~~~~~~~~~ should be gimage2DRect
```

**Comment by gnl21** [comment]
Thanks for the report. I've made the changes that you suggest, so (subject to approval) they should be fixed in the next spec release.

**Comment by gnl21** [comment]
This is fixed in spec revision 8.
