### ISSUE TITLE
Want pass-by-reference function-call syntax to avoid implication of doing large copies.

### ISSUE THREAD

**Issue by greg-lunarg** [KhronosGroup/GLSL#176]
See https://github.com/KhronosGroup/GLSL/issues/84

**Comment by pdaniell-nv** [comment]
The old https://github.com/KhronosGroup/GLSL/issues/84 issue was already in the GLSL repo. It's not clear to me why a new issue referencing that old issue was opened here. @greg-lunarg can you add to the description.

**Comment by greg-lunarg** [comment]
Sorry. Brain freeze. I thought #84 was a glslang issue. I am reopening #84 and closing this.
