### ISSUE TITLE
ESSL specification appendix was wrong.   (version before gpu_shader5) 

### ISSUE THREAD

**Issue by absinthe99** [KhronosGroup/GLSL#2]
According to Khronos GLES 3.1 ES shader language specification,

I see this version of specification and before.

--
Language Version: 3.10
Document Revision: 4
29 January 2016
Editor: Robert J. Simpson, Qualcomm
--

I found a strange notation like as below.  
last RESOLUTION paragraph clearly said that dynamic indexing of sampler arrays is now prohibited.
but other paragraph said allowed as if indexing is allowed.　It seems contradictory notations.
What does mean this allowed?  
As we know before gpu_shader5 extension ESSL doesn't have dynamically indexing for sampler.
This paragraph will only induce us misread.
Main purpose of this paragraph is only l-value not indexing. This paragraph about indexing should be omitted. 
--

13.29 Samplers
Should samplers be allowed as l-values? The specification already allows an equivalent behavior:
Current specification: uniform sampler2D sampler8;

　int index = f(...);
　vec4 tex = texture(sampler[index], xy); // allowed

Using assignment of sampler types:

　uniform sampler2D s;
　s = g(...);
　vec4 tex = texture(s, xy); // not allowed

RESOLUTION: Dynamic indexing of sampler arrays is now prohibited by the specification. Restrict
indexing of sampler arrays to constant integral expressions.

**Comment by johnkslang** [comment]
Khronos discussed, and the issues/resolutions in that section are out of date, and hence confusing and should probably be ignored and in the future deleted.

**Comment by pdaniell-nv** [comment]
Assigning Tobias in lieu of Robert.

**Comment by pdaniell-nv** [comment]
@gnl21 Do you know if this spec got this fix?

**Comment by gnl21** [comment]
Yes, this fix is in the latest published spec.
