### ISSUE TITLE
Are built-in constants a constant expressions?

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/GLSL#20]
The [OpenGL wiki](https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)#Constants) says:

> All of these variables are declared as const, so they are considered constant expressions.

But that is not so obvious to me from the spec:

> A variable declared with the const qualifier and an initializer, where the initializer is a constant
expression.

Built-ins are not really explicitly declared. And do not really have an initializer.
Would it be nice to add them to the list of constant expressions explicitly?

**Comment by johnkslang** [comment]
No, many built-in variables are actually not compile-time constant expressions, and cannot be used as **const**.

However, there are a bunch of built-in constants. That is what is being discussed regarding your wiki quote.

The spec typically does show the internal declaration for both built-in variables and built-in constants, and uses **const** as is appropriate.

**Comment by johnkslang** [comment]
I think I see what your point is now. The declarations in the specification are indeed to be taken as real declarations, implying everything that declaration implies. In section 7.3 "Built-In Constants" We can change:

> The following built-in constants are provided to all shaders.

to

> The following built-in constants are declared in all shaders.

**Comment by krOoze** [comment]
@johnkslang It would need to say "declared and having an initializer". I would think just listing built-in constants explicitly as constexprs would be simpler...

**Comment by johnkslang** [comment]
We don't want to go down the path of all built-in declarations having to be called out independently each time there is a rule that discusses a keyword. The declarations should all automatically get included, based on their syntax from the specification.

> It would need to say "declared and having an initializer that is constexpr".

We can include that. It didn't occur to me, because of this rule that we have:

> Initializers for const declarations at global scope must be constant expressions, as defined in section 4.3.3 “Constant Expressions.”

**Comment by johnkslang** [comment]
Maybe that last comment applied to the wiki?  For the specification, it really seems sufficient to change to:

> The following built-in constants are declared in all shaders.

Which is what I am tentatively doing.

Note they do in fact have constant-expression initializers *and* are at global scope, independently invoking two different existing rules that say the result is a constant expression, so I don't think that section is the right place to re-explain any of that.

**Comment by johnkslang** [comment]
This is done now, via https://gitlab.khronos.org/opengl/GLSL/merge_requests/65. The constants otherwise already satisfy the definitions to be constant expressions.
