### ISSUE TITLE
Is GLSL had some online document?

### ISSUE THREAD

**Issue by FuXiii** [KhronosGroup/GLSL#206]
When I check `Vulkan API`  document. I can visit https://www.khronos.org/registry/vulkan/specs/1.3/html/index.html .Is GLSL had some online document like this?

If I want check the definition about `gl_LaunchSizeEXT` the only way is check the [GLSL_EXT_ray_tracing](https://github.com/KhronosGroup/GLSL/blob/883a2113d8ab3cbf0cc534989a90ba1bb0ba6a11/extensions/ext/GLSL_EXT_ray_tracing.txt#L716).

**Comment by pdaniell-nv** [comment]
For GLSL the extensions are written as diffs against the main specification. The main specification is here: https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html. The Vulkan GLSL extensions are here: https://github.com/KhronosGroup/GLSL/tree/master#extension-specifications-in-this-repository. There is no single GLSL document that combines the main specification with the extensions.

**Comment by FuXiii** [comment]
Ok, thanks~ (๑•̀ㅂ•́)و✧
