### ISSUE TITLE
Khronos GLSL grammar 4.60.7 has missing parameter-type for "P" in "textureGrad"

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/GLSL#207]
See the red marking.

![Screenshot 2023-06-13 160404](https://github.com/KhronosGroup/GLSL/assets/16970147/18a54463-5190-4132-8d90-a4e32ac82feb)

**Comment by pdaniell-nv** [comment]
Thanks for point out this issue. This is fixed in our main branch and the fix will be included in the next spec update.

**Comment by pdaniell-nv** [comment]
This is fixed in the latest specs: [HTML](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html) [PDF](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf).
