### ISSUE TITLE
GLSL grammar allows for statements like "float;" but does not say they're invalid

### ISSUE THREAD

**Issue by AndrewRayCode** [KhronosGroup/GLSL#209]
The Khronos grammar allows for do-nothing, nonsensical statements like `float;` and `void;`.

That's because the grammar for declaration has this possible production path:

```
declaration :
   init_declarator_list SEMICOLON

init_declarator_list :
   single_declaration

single_declaration :
   fully_specified_type

fully_specified_type :
   type_specifier

type_specifier :
   type_specifier_nonarray

type_specifier_nonarray :
   VOID
   ...
   struct_specifier
   TYPE_NAME
```

I believe the intent of this code path is to allow for `struct_specifier SEMICOLON` as a declaration, like
```glsl
struct X { float y; };
```
With that final semicolon matching it against the `declaration` production.

Because `TYPE_NAME` is in there, the grammar also allows for do-nothing statements of declared types, like
```glsl
struct X { float y; };
X;
```

I propose that either:
- The specification doc introduces a semantic rule that `float;` etc are not valid statements, OR
- The grammar be updated to make this parse path impossible. I'm guessing this was done for convenience of the grammar to avoid having to duplicate `fully_specified_type` into `fully_specified_type_struct_specifier_only` or something like that. Although after seeing how `postfix_expression` was (hastily?) implemented, I question the trade-offs made of a simpler grammar vs a more explicit one.

These statements parse in ANGLE as well. So this would be a breaking change.

**Comment by pdaniell-nv** [comment]
There is a section in the GLSL and ESSL specs that describe empty declaration which handle this case:
- GLSL: https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html#empty-declarations
- ESSL: https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.html#empty-declarations
