### ISSUE TITLE
Precise calculation and branch conditions

### ISSUE THREAD

**Issue by stevec611** [KhronosGroup/GLSL#21]
Given
```
#version 450

layout (location = 0) in float x;
layout (location = 1) in float y;
layout (location = 2) in float z;

precise gl_Position;

void main(void)
{
    gl_Position.xyzw = vec4(0.0);
    if ((x * y + z) > 0.0) {
        gl_Position.x = 1.0;
    } else {
        gl_Position.x = 2.0;
    }
}
```
Does the `precise` on `gl_Position` apply to the calculation `x * y + z`?

**Comment by johnkslang** [comment]
I suspect control flow is not intended to be included.  We will resolve inside Khronos, but first give relevant language.

The specification starts with the broad statement:

> The qualifier **precise** will ensure that operations contributing to a variable's value are done in their stated order and are done with operator consistency. 

However, it is not the complete rule, as it goes on to say **precise** does not cross function boundaries, as well as essentially say flow control is not included:

> This qualifier will affect the evaluation of an r-value in a particular function if and only if the result is
eventually consumed in the same function by an l-value qualified as **precise**. Any other expressions
within a function are not affected, including return values and output parameters not declared as **precise** but that are eventually consumed outside the function by a variable qualified as **precise**.

The expression ` (x * y + z) > 0.0` is an r-value that is never consumed by an l-value, so falls outside the rules stated in the last quote above.

Further, none of the examples or discussion include or imply control flow interaction, except for saying it does not include crossing function boundaries.

I suspect the list "...including return values and output parameters not declared as **precise**..." should be expanded to include control flow.

**Comment by stevec611** [comment]
I'm not sure I want to prompt a discussion about exactly what _consumed_ means in this context :)  
But it would be nice to have a clarification on whether `a` consumes `c` in
 `a = c ? X : Y;`

**Comment by johnkslang** [comment]
FYI, current glslang behavior is that for 

```
precise float r = a * b > 5 ? f + g : f - g;
```

the `+` and `-` are decorated **NoContraction**, while the `*` is not.

There is some logical consistency here, but will refrain from making a judgment just yet.

**Comment by johnkslang** [comment]
Khronos decided that neither control flow expressions nor the condition in a `? :` are subject to the propagation of `precise`.

We will clarify the specification.

**Comment by johnkslang** [comment]
This fix was published in December in Rev. 6 of the 4.60 GLSL specification.
