### ISSUE TITLE
"&=" in the docs

### ISSUE THREAD

**Issue by robertschulman1** [KhronosGroup/GLSL#241]
In the May 12, 2009 edition of The OpenGL ES Shading Language, the "&=" operator is mentioned in the table in Section 5.1. Other arithmetic assignment operators are also mentioned in this table. Later in the text, in Section 5.8, these other operators are mentioned. Some are called out as reserved (eg. <<=). The "&=" operator is not mentioned in the list of reserved operators in Section 5.8. It should be.

**Comment by dj2** [comment]
Is this still an issue in the latest version of the spec? I see the `&=` in the table in 5.1, but in 5.8 it's mentioned in the bulleted list `and into (&=)`.

I'm looking at [The GLSL ES Specification 3.20](https://registry.khronos.org/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf) sections 5.1 and 5.8, should I be looking somewhere else?

**Comment by oddhack** [comment]
I'll ping the OpenGL WG chair @zmike, but fixing a 15 year old typo is not going to be high up anyone's priority list.

**Comment by dj2** [comment]
Sorry for not being clear, that was a question to the original requestor. I can't find the problem in the current spec, so I suspect this can be closed, but I maybe looking in the wrong spot.

**Comment by zmike** [comment]
I see the correct documentation for `&=` in the existing spec (Version 3.20.8, Mon, 14 Aug 2023). It looks like OP is just reading from an older version. I don't think there's anything to do here.

**Comment by oddhack** [comment]
Closing as WONTFIX due to the age of the spec the problem appears in.

**Comment by oddhack** [comment]
WONTFIX.

**Comment by oddhack** [comment]
Maybe clicking on the wrong button?

**Comment by robertschulman1** [comment]
*whew*

On 2024-11-06 09:15, Jon Leech wrote:

> Closed #241 [1] as completed.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/KhronosGroup/GLSL/issues/241
[2] https://github.com/KhronosGroup/GLSL/issues/241#event-15150971383
[3]
