### ISSUE TITLE
texelFetch cannot be used with texture2D

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/GLSL#25]
SPIR-V uses texelFetch without a sampler, and so does HLSL, but not GLSL, where you need a combined image sampler (for legacy reasons I assume). This causes interoperability issues between HLSL and GLSL.

A bug was filed to SPIRV-Cross which cannot be solved properly without a fix to Vulkan GLSL. https://github.com/KhronosGroup/SPIRV-Cross/issues/424

**Comment by jeffbolznv** [comment]
Isn't this already solved by https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_samplerless_texture_functions.txt?

**Comment by HansKristian-ARM** [comment]
Oh, right, I forgot about that. Just had some very old issue lying around.
