### ISSUE TITLE
GLSL 4.60: Missing mention of application of storage block names.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/GLSL#3]
In 4.3.9: Interface Blocks, the specification says:

> For uniform blocks, the application uses the block name to identify the block.

This should be for both uniform and storage blocks.

The same goes for:

> Matched uniform block names (but not input or output block names) must also either all be lacking an instance name or all having an instance name, putting their members at the same scoping level.

**Comment by NicolBolas** [comment]
There are a couple of other places where `buffer` is not mentioned where it ought to be. For example, section 4.4:

> They can also appear with just an interface qualifier (a storage qualifier that is `in`, `out`, or `uniform`) to establish layouts of other declarations made with that interface qualifier:

**Comment by ThorStrikesAgain** [comment]
I found a potentially related issue in section 4.4.5:
> The binding identifier specifies the **uniform** buffer binding point corresponding to the **uniform** or **shader storage** block, which will be used to obtain the values of the member variables of the block.

Maybe we should read, instead:

> The binding identifier specifies the **uniform** or **shader storage** buffer binding point corresponding to the **uniform** or **shader storage** block, which will be used to obtain the values of the member variables of the block.

**Comment by dgkoch** [comment]
WG-2017-09-01 - agree with suggestions. Assigning to JohnK to incorporate the suggestions as appropriate.

**Comment by TobiasHector** [comment]
NB: These are already fixed in the ESSL specification, so we should probably make the language match up.

**Comment by pdaniell-nv** [comment]
@johnkslang Did the GLSL spec get this fix yet?

**Comment by pdaniell-nv** [comment]
This has been fixed in the latest GLSL 4.60.5 spec: https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf
