### ISSUE TITLE
GL_EXT_shader_8bit_storage doesn't have an extension file

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/GLSL#30]
You can use GL_EXT_shader_8bit_storage in latest glslang, but this repository doesn't have a spec for it. I'm guessing it's basically the same as GL_EXT_shader_16bit_storage but would be good to have a reference text regardless.

**Comment by jeffbolznv** [comment]
The 8bit extension is specified in the same file as the 16bit extension: https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_shader_16bit_storage.txt.

**Comment by zeux** [comment]
Ah, I missed this. Thanks!

**Comment by sheredom** [comment]
(Given that a couple of people have now made this mistake, maybe we should make a simple/stupid extension file for GL_EXT_shader_8bit_storage that just points at the GL_EXT_shader_16bit_storage one?)

**Comment by jeffbolznv** [comment]
We have other examples of extension specs that include multiple extension strings, e.g. https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_shader_subgroup.txt. I guess this one is a little less obvious. I don't really object, I just don't think it's necessary. The first hit on Google finds the right file.
