### ISSUE TITLE
GL_NV_mesh_shader spec typo for per-primitive fragment shader inputs

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/GLSL#31]
The extension spec says:

```
    (add a new example to the second paragraph, p. 48)

      primitive in vec3 triangleNormal;
```

But it should use `perprimitiveNV` instead as far as I understand (perprimitiveNV is accepted by glslang, primitive isn't).

**Comment by sparmarNV** [comment]
PR #32 has been merged. This can be closed.

**Comment by zeux** [comment]
Perfect, thanks!
