### ISSUE TITLE
GLSL 4.60: No mention of TCS/TES in array block matching rules

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/GLSL#4]
Consider this from 4.3.9:

> Furthermore, if a matching block is declared as an array, then the array sizes must also match (or follow array matching rules for the shader interface between a vertex and a geometry shader). 

Array matching rules are also different for TCS/TES stages. I'd suggest changing it to:

> Furthermore, if a matching block is declared as an array, then the array sizes must also match, in accord with the array matching rules for the shader interface between the two stages.

Or something of the sort.

**Comment by dgkoch** [comment]
WG 2017-09-01 - decided we should describe these by enumeration instead of description, and assigning to JohnK to implement in the spec.

**Comment by johnkslang** [comment]
The interfaces that have an extra level of arrayness are:

- geometry input
- tessellation control input, for non-patch
- tessellation control output, for non-patch
- tessellation evaluation input, for non-patch

**Comment by TobiasHector** [comment]
This affects ES as well, so assigning to myself for discussion in the next meeting.

**Comment by TobiasHector** [comment]
Assigning to Piers to discuss with the OpenGL ES group

**Comment by pdaniell-nv** [comment]
Discussed in the OpenGL|ES meeting today. Agreed we need to apply the same fix to the ESSL spec.

**Comment by pdaniell-nv** [comment]
@johnkslang Do you know if we applied this fix yet?

**Comment by pdaniell-nv** [comment]
This appears to be clarified in the latest GLSL 4.60.5 spec: https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf

Now it says:

  ... Furthermore, if a matching
  block is declared as an array, then the array sizes must also match (or follow array matching rules
  for the shader interface between consecutive shader stages).
