### ISSUE TITLE
Clarification on subgroupBallotExclusiveBitCount/subgroupBallotInclusiveBitCount

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/GLSL#48]
https://github.com/KhronosGroup/GLSL/blob/a27d36df7631734f0aec4053db54095cf2defe55/extensions/khr/GL_KHR_shader_subgroup.txt#L879

Do those only count bits for active subgroup invocations? Or do I manually need to mask with gl_SubgroupEqMask?

Usually for a scan operation you only want to consider active threads.

**Comment by dgkoch** [comment]
cc @jeffbolznv @sheredom 

Does https://www.khronos.org/assets/uploads/developers/library/2018-vulkan-devday/06-subgroups.pdf slides 12 and 13 help to clarify at all?

To answer your original question (the difference between inclusive and exclusive bitcount), 
In general: 
subgroupBallotInclusiveBitCount(val) == subgroupBallotBitCount(val & gl_SubgroupLeMask)
and 
subgroupBallotExclusiveBitCount(val) == subgroupBallotBitCount(val & gl_SubgroupLtMask)

ie "inclusive" counts bits for the active invocations <= current invocation
"exclusive" counts bits for the active invocations < current invocation.

**Comment by Novum** [comment]
Seems like the intention is really to use it together with the active thread mask. Thanks.

The confusion came from how AMD documented mbcnt in older documents.
