### ISSUE TITLE
 [GL_NV_ray_tracing] Is shaderRecordNV buffer readonly or writable?

### ISSUE THREAD

**Issue by linqun** [KhronosGroup/GLSL#56]
Per Vulkan spec:
The shader binding tables to use in a ray tracing query are passed to vkCmdTraceRaysNV. Shader binding tables are read-only in shaders that are executing on the ray tracing pipeline.

But in GL_NV_ray_tracing spec,  layout shaderRecordNV only can be bound to buffer and it is writable in glslang test spv.RayGenShader.rgen.

Could you help to clarify which one is expected? thanks!

**Comment by dgkoch** [comment]
(working on figuring out the answer to this)

**Comment by dgkoch** [comment]
Spec fix: https://github.com/KhronosGroup/GLSL/pull/60
Gslslang fix: https://github.com/KhronosGroup/glslang/pull/1728

**Comment by dgkoch** [comment]
Fixes have been merged.

**Comment by linqun** [comment]
Got it. Thank you very much!
