### ISSUE TITLE
Subgroup variables not supported in Ray Tracing Shaders

### ISSUE THREAD

**Issue by Max1412** [KhronosGroup/GLSL#65]
This only affects the GL_NV_ray_tracing extension.
I noticed that `gl_SubgroupSize` and `gl_SubgroupInvocationID` are not available in ray tracing shaders, especially in ray generation shaders, while the same shaders using subgroup functions like `subgroupBarrier()` are compiling just fine. Is this a missing feature or just not supported at all?

**Comment by dgkoch** [comment]
They should be yes (at least NVIDIA's implementation supports them, and this is reported via VkPhysicalDeviceSubgroupProperties::supportedStages).  

Is this failing to compile in glslang?  If so, please file a bug there (with failing shader). 

We should probably also figure out which spec this should be noted in as well..

**Comment by Max1412** [comment]
It does not compile with glslangvalidator and glslc. I opened the issue here because GL_NV_ray_tracing does not add to the spec that e.g. `gl_SubgroupInvocationID` should be available in the e.g. ray generation shader stage, as GL_KHR_shader_subgroup does (section 7.1 of the spec).

**Comment by johnkslang** [comment]
Linking to the apparent glslang issue for this:  https://github.com/KhronosGroup/glslang/issues/1735.

**Comment by dgkoch** [comment]
This has definitely been address by the final KHR release https://github.com/KhronosGroup/Vulkan-Docs/issues/1402 
(although I believe most of it was fixed earlier).

**Comment by dgkoch** [comment]
Hrm. maybe still some spec interactions to be documented in the GLSL extension.
