### ISSUE TITLE
Improve docs for gl_ClipDistance: Interface blocks can't be redeclared in GLSL < 4.10

### ISSUE THREAD

**Issue by HorstBaerbel** [KhronosGroup/GLSL#69]
Redeclaring blocks needs GL_ARB_separate_shader_objects or #version 410. When redeclaring gl_ClipDistance[] with a specific array size you have to use:
`out float gl_ClipDistance[6];`
The [wiki page](https://www.khronos.org/opengl/wiki/Vertex_Post-Processing) does not state a specific version requirement. The [reference page](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_ClipDistance.xhtml) and the [built-ins wiki page](https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)) don't either. The GLSL 3.3 language specs say redeclaring built in variables it forbidden unless specifically allowed for certain variables, so that probably covers it, but is easy to miss. Some implementations seem to complain, some don't.
See also [this issue](https://github.com/KhronosGroup/glslang/issues/1441).

**Comment by pdaniell-nv** [comment]
I have put in a request to update the two wiki pages. If you want to reference page improved, could you file an issue here: https://github.com/KhronosGroup/OpenGL-Refpages. Thanks.

Since this isn't an issue with the GLSL specs I'm closing this issue.
