### ISSUE TITLE
Want pass-by-reference function-call syntax to avoid implication of doing large copies.

### ISSUE THREAD

**Issue by Raikiri** [KhronosGroup/GLSL#84]
Here's my minimal test code:
```cpp
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec2 fragScreenCoord;
layout(location = 0) out vec4 resColor;

#define MaxObjectsCount 20
struct Object
{
  uint bla1;
  uint bla2;
};

struct Objects
{
  Object data[MaxObjectsCount];
};

Objects objects;

void CompareExchange(/*inout Objects objects, */uint i, uint j)
{
  if(objects.data[i].bla1 > objects.data[j].bla1)
  {
    Object tmp = objects.data[i];
    objects.data[i] = objects.data[j];
    objects.data[j] = tmp;
  }
}
void main()
{
  resColor = vec4(1.0f, 0.5f, 0.0f, 1.0f);
  for(int i = 0; i < MaxObjectsCount; i++)
  {
    objects.data[i].bla1 = uint(gl_FragCoord.x) - i;
    objects.data[i].bla2 = uint(gl_FragCoord.y) + i;
  }
  for(int i = 0; i < MaxObjectsCount; i++)
  {
    for(int j = 0; j < MaxObjectsCount - i - 1; j++)
    {
      CompareExchange(/*objects, */j, j + 1);
    }
  }
  resColor.r += objects.data[0].bla1 * 1e-3f;
}


```
This code runs in fragment shader and takes approximately 30ms on my GTX1050. Uncommenting the function argument makes this code run approximately 20(!) times slower to about 650ms. The results are the same both in OpenGL application that uses glCompileShader() and in Vulkan that uses glslang to compile this glsl into spirv.

So my questions are: why is there no syntax for proper function inlining to make sure that this does not happen? Why is there no syntax for proper pass-by-reference instead of pass-by-copy-in/copy-out semantic "inout"?

**Comment by Raikiri** [comment]
I understand the reasoning why according to the spec compiler is allowed to do a copy here. However, Even in a code like this:
```cpp
void CompareExchange(inout Objects objects, uint i, uint j)
{
  objects.data[i] = objects.data[j];
}
void main()
{
  Objects objects;
  CompareExchange(objects, i, j);
}
```
It still copies the local variable even though it's accessed in a pretty straightforward fashion. And worst of all, there is no easy workaround to avoid copying except for using a macro instead of a function or jumping through hoops with global variables.

**Comment by Raikiri** [comment]
For a background of why this might be important: using a function like 
```cpp
void DoSomething(LargeObject obj, /*args*/)
```
is the closest thing we have in shading languages to class methods like
```cpp
obj->DoSomething(/*args*/);
```
and of course no one expects a copy of an object to be created when its method is called. However, working around this ambiguity can be unnecessarily ugly involving singleton-like globals or macros.

**Comment by Raikiri** [comment]
Further testing revealed that this bug seems to be related to nvidia drivers because running test code on Intel GPU gives the same performance on both versions: with a global variable and with a function argument. Additionally, I got a disassembly of an actual shader that the driver runs using https://github.com/pixeljetstream/glslc 
Here's a version with global variables:
```
!!NVfp5.0 
OPTION NV_internal; 
OPTION NV_bindless_texture; 
ATTRIB fragment_position = fragment.position; 
TEMP R0, R1, R2; 
TEMP T; 
TEMP RC, HC; 
TEMP lmem0[40]; 
OUTPUT result_color0 = result.color; 
MOV.F result_color0, {1, 0.5, 0, 0}.xyzx; 
MOV.S R0.x, {0, 0, 0, 0}; 
REP.S {20, 0, 0, 0}; 
TRUNC.U R0.y, fragment.position.x; 
ADD.U R0.z, -R0.x, R0.y; 
MUL.S R0.y, R0.x, {2, 0, 0, 0}.x; 
MOV.S R0.y, R0; 
MOV.U lmem0[R0.y].x, R0.z; 
TRUNC.U R0.w, fragment.position.y; 
ADD.U R0.z, R0.x, R0.w; 
MOV.U lmem0[R0.y + 1].x, R0.z; 
ADD.S R0.x, R0, {1, 0, 0, 0}; 
ENDREP; 
MOV.S R0.y, {0, 0, 0, 0}.x; 
REP.S {20, 0, 0, 0}; 
MOV.S R0.z, {0, 0, 0, 0}.x; 
REP.S ; 
ADD.S R0.x, -R0.y, {20, 0, 0, 0}; 
ADD.S R0.x, R0, -{1, 0, 0, 0}; 
SGE.S.CC HC.x, R0.z, R0; 
BRK (NE.x); 
ADD.S R0.w, R0.z, {1, 0, 0, 0}.x; 
MUL.S R1.x, R0.w, {2, 0, 0, 0}; 
MUL.S R0.x, R0.z, {2, 0, 0, 0}; 
MOV.S R1.y, R1.x; 
MOV.S R1.x, R0; 
MOV.U R0.x, lmem0[R1.y].x; 
MOV.U R1.x, lmem0[R1.x].x; 
SGT.U R0.x, R1, R0; 
MOV.U.CC RC.x, -R0; 
IF NE.x; 
MUL.S R1.x, R0.w, {2, 0, 0, 0}; 
MOV.S R1.y, R1.x; 
MUL.S R0.x, R0.z, {2, 0, 0, 0}; 
MOV.S R0.w, R0.x; 
MOV.U R0.x, lmem0[R0.w].x; 
MOV.U R2.x, lmem0[R1.y].x; 
MOV.U R1.x, lmem0[R0.w + 1].x; 
MOV.U lmem0[R0.w].x, R2; 
MOV.U R2.x, lmem0[R1.y + 1].x; 
MOV.U lmem0[R0.w + 1].x, R2; 
MOV.U lmem0[R1.y].x, R0; 
MOV.U lmem0[R1.y + 1].x, R1; 
ENDIF; 
ADD.S R0.z, R0, {1, 0, 0, 0}.x; 
ENDREP; 
ADD.S R0.y, R0, {1, 0, 0, 0}.x; 
ENDREP; 
MOV.U R0.x, lmem0[0].x; 
I2F.U R0.x, R0; 
MAD.F result_color0.x, R0, {0.00100000005, 1, 0, 0}, {0.00100000005, 1, 0, 0}.y; 
END
```
and here's a version with function arguments:
```
!!NVfp5.0 
OPTION NV_internal; 
OPTION NV_bindless_texture; 
ATTRIB fragment_position = fragment.position; 
TEMP R0, R1, R2; 
TEMP T; 
TEMP RC, HC; 
TEMP lmem0[80]; 
OUTPUT result_color0 = result.color; 
MOV.F result_color0, {1, 0.5, 0, 0}.xyzx; 
MOV.S R0.x, {0, 0, 0, 0}; 
REP.S {20, 0, 0, 0}; 
TRUNC.U R0.y, fragment.position.x; 
ADD.U R0.z, -R0.x, R0.y; 
MUL.S R0.y, R0.x, {2, 0, 0, 0}.x; 
MOV.S R0.y, R0; 
MOV.U lmem0[R0.y].x, R0.z; 
TRUNC.U R0.w, fragment.position.y; 
ADD.U R0.z, R0.x, R0.w; 
MOV.U lmem0[R0.y + 1].x, R0.z; 
ADD.S R0.x, R0, {1, 0, 0, 0}; 
ENDREP; 
MOV.S R0.y, {0, 0, 0, 0}.x; 
REP.S {20, 0, 0, 0}; 
MOV.S R0.z, {0, 0, 0, 0}.x; 
REP.S ; 
ADD.S R0.x, -R0.y, {20, 0, 0, 0}; 
ADD.S R0.x, R0, -{1, 0, 0, 0}; 
SGE.S.CC HC.x, R0.z, R0; 
BRK (NE.x); 
MOV.U R0.x, lmem0[0].x; 
MOV.U lmem0[40].x, R0; 
MOV.U R0.x, lmem0[1].x; 
MOV.U lmem0[41].x, R0; 
MOV.U R0.x, lmem0[2].x; 
MOV.U lmem0[42].x, R0; 
MOV.U R0.x, lmem0[3].x; 
MOV.U lmem0[43].x, R0; 
MOV.U R0.x, lmem0[4].x; 
MOV.U lmem0[44].x, R0; 
MOV.U R0.x, lmem0[5].x; 
MOV.U lmem0[45].x, R0; 
MOV.U R0.x, lmem0[6].x; 
MOV.U lmem0[46].x, R0; 
MOV.U R0.x, lmem0[7].x; 
MOV.U lmem0[47].x, R0; 
MOV.U R0.x, lmem0[8].x; 
MOV.U lmem0[48].x, R0; 
MOV.U R0.x, lmem0[9].x; 
MOV.U lmem0[49].x, R0; 
MOV.U R0.x, lmem0[10].x; 
MOV.U lmem0[50].x, R0; 
MOV.U R0.x, lmem0[11].x; 
MOV.U lmem0[51].x, R0; 
MOV.U R0.x, lmem0[12].x; 
MOV.U lmem0[52].x, R0; 
MOV.U R0.x, lmem0[13].x; 
MOV.U lmem0[53].x, R0; 
MOV.U R0.x, lmem0[14].x; 
MOV.U lmem0[54].x, R0; 
MOV.U R0.x, lmem0[15].x; 
MOV.U lmem0[55].x, R0; 
MOV.U R0.x, lmem0[16].x; 
MOV.U lmem0[56].x, R0; 
MOV.U R0.x, lmem0[17].x; 
MOV.U lmem0[57].x, R0; 
MOV.U R0.x, lmem0[18].x; 
MOV.U lmem0[58].x, R0; 
MOV.U R0.x, lmem0[19].x; 
MOV.U lmem0[59].x, R0; 
MOV.U R0.x, lmem0[20].x; 
MOV.U lmem0[60].x, R0; 
MOV.U R0.x, lmem0[21].x; 
MOV.U lmem0[61].x, R0; 
MOV.U R0.x, lmem0[22].x; 
MOV.U lmem0[62].x, R0; 
MOV.U R0.x, lmem0[23].x; 
MOV.U lmem0[63].x, R0; 
MOV.U R0.x, lmem0[24].x; 
MOV.U lmem0[64].x, R0; 
MOV.U R0.x, lmem0[25].x; 
MOV.U lmem0[65].x, R0; 
MOV.U R0.x, lmem0[26].x; 
MOV.U lmem0[66].x, R0; 
MOV.U R0.x, lmem0[27].x; 
MOV.U lmem0[67].x, R0; 
MOV.U R0.x, lmem0[28].x; 
MOV.U lmem0[68].x, R0; 
MOV.U R0.x, lmem0[29].x; 
MOV.U lmem0[69].x, R0; 
MOV.U R0.x, lmem0[30].x; 
MOV.U lmem0[70].x, R0; 
MOV.U R0.x, lmem0[31].x; 
MOV.U lmem0[71].x, R0; 
MOV.U R0.x, lmem0[32].x; 
MOV.U lmem0[72].x, R0; 
MOV.U R0.x, lmem0[33].x; 
MOV.U lmem0[73].x, R0; 
MOV.U R0.x, lmem0[34].x; 
MOV.U lmem0[74].x, R0; 
MOV.U R0.x, lmem0[35].x; 
MOV.U lmem0[75].x, R0; 
MOV.U R0.x, lmem0[36].x; 
MOV.U lmem0[76].x, R0; 
MOV.U R0.x, lmem0[37].x; 
MOV.U lmem0[77].x, R0; 
MUL.S R0.w, R0.z, {2, 0, 0, 0}.x; 
MOV.U R0.x, lmem0[38].x; 
MOV.U lmem0[78].x, R0; 
MOV.S R1.x, R0.w; 
MOV.U R0.x, lmem0[39].x; 
MOV.U lmem0[79].x, R0; 
ADD.S R0.w, R0.z, {1, 0, 0, 0}.x; 
MUL.S R1.y, R0.w, {2, 0, 0, 0}.x; 
MOV.S R0.x, R1.y; 
MOV.U R0.x, lmem0[R0.x].x; 
MOV.U R1.x, lmem0[R1.x].x; 
SGT.U R0.x, R1, R0; 
MOV.U.CC RC.x, -R0; 
IF NE.x; 
MUL.S R1.x, R0.w, {2, 0, 0, 0}; 
MOV.S R1.y, R1.x; 
MUL.S R0.x, R0.z, {2, 0, 0, 0}; 
MOV.S R0.w, R0.x; 
MOV.U R0.x, lmem0[R0.w].x; 
MOV.U R2.x, lmem0[R1.y].x; 
MOV.U R1.x, lmem0[R0.w + 1].x; 
MOV.U lmem0[R0.w + 40].x, R2; 
MOV.U R2.x, lmem0[R1.y + 1].x; 
MOV.U lmem0[R0.w + 41].x, R2; 
MOV.U lmem0[R1.y + 40].x, R0; 
MOV.U lmem0[R1.y + 41].x, R1; 
ENDIF; 
MOV.U R0.x, lmem0[40].x; 
MOV.U lmem0[0].x, R0; 
MOV.U R0.x, lmem0[41].x; 
MOV.U lmem0[1].x, R0; 
MOV.U R0.x, lmem0[42].x; 
MOV.U lmem0[2].x, R0; 
MOV.U R0.x, lmem0[43].x; 
MOV.U lmem0[3].x, R0; 
MOV.U R0.x, lmem0[44].x; 
MOV.U lmem0[4].x, R0; 
MOV.U R0.x, lmem0[45].x; 
MOV.U lmem0[5].x, R0; 
MOV.U R0.x, lmem0[46].x; 
MOV.U lmem0[6].x, R0; 
MOV.U R0.x, lmem0[47].x; 
MOV.U lmem0[7].x, R0; 
MOV.U R0.x, lmem0[48].x; 
MOV.U lmem0[8].x, R0; 
MOV.U R0.x, lmem0[49].x; 
MOV.U lmem0[9].x, R0; 
MOV.U R0.x, lmem0[50].x; 
MOV.U lmem0[10].x, R0; 
MOV.U R0.x, lmem0[51].x; 
MOV.U lmem0[11].x, R0; 
MOV.U R0.x, lmem0[52].x; 
MOV.U lmem0[12].x, R0; 
MOV.U R0.x, lmem0[53].x; 
MOV.U lmem0[13].x, R0; 
MOV.U R0.x, lmem0[54].x; 
MOV.U lmem0[14].x, R0; 
MOV.U R0.x, lmem0[55].x; 
MOV.U lmem0[15].x, R0; 
MOV.U R0.x, lmem0[56].x; 
MOV.U lmem0[16].x, R0; 
MOV.U R0.x, lmem0[57].x; 
MOV.U lmem0[17].x, R0; 
MOV.U R0.x, lmem0[58].x; 
MOV.U lmem0[18].x, R0; 
MOV.U R0.x, lmem0[59].x; 
MOV.U lmem0[19].x, R0; 
MOV.U R0.x, lmem0[60].x; 
MOV.U lmem0[20].x, R0; 
MOV.U R0.x, lmem0[61].x; 
MOV.U lmem0[21].x, R0; 
MOV.U R0.x, lmem0[62].x; 
MOV.U lmem0[22].x, R0; 
MOV.U R0.x, lmem0[63].x; 
MOV.U lmem0[23].x, R0; 
MOV.U R0.x, lmem0[64].x; 
MOV.U lmem0[24].x, R0; 
MOV.U R0.x, lmem0[65].x; 
MOV.U lmem0[25].x, R0; 
MOV.U R0.x, lmem0[66].x; 
MOV.U lmem0[26].x, R0; 
MOV.U R0.x, lmem0[67].x; 
MOV.U lmem0[27].x, R0; 
MOV.U R0.x, lmem0[68].x; 
MOV.U lmem0[28].x, R0; 
MOV.U R0.x, lmem0[69].x; 
MOV.U lmem0[29].x, R0; 
MOV.U R0.x, lmem0[70].x; 
MOV.U lmem0[30].x, R0; 
MOV.U R0.x, lmem0[71].x; 
MOV.U lmem0[31].x, R0; 
MOV.U R0.x, lmem0[72].x; 
MOV.U lmem0[32].x, R0; 
MOV.U R0.x, lmem0[73].x; 
MOV.U lmem0[33].x, R0; 
MOV.U R0.x, lmem0[74].x; 
MOV.U lmem0[34].x, R0; 
MOV.U R0.x, lmem0[75].x; 
MOV.U lmem0[35].x, R0; 
MOV.U R0.x, lmem0[76].x; 
MOV.U lmem0[36].x, R0; 
MOV.U R0.x, lmem0[77].x; 
MOV.U lmem0[37].x, R0; 
MOV.U R0.x, lmem0[78].x; 
MOV.U lmem0[38].x, R0; 
MOV.U R0.x, lmem0[79].x; 
MOV.U lmem0[39].x, R0; 
ADD.S R0.z, R0, {1, 0, 0, 0}.x; 
ENDREP; 
ADD.S R0.y, R0, {1, 0, 0, 0}.x; 
ENDREP; 
MOV.U R0.x, lmem0[0].x; 
I2F.U R0.x, R0; 
MAD.F result_color0.x, R0, {0.00100000005, 1, 0, 0}, {0.00100000005, 1, 0, 0}.y; 
END
```
Apparently nvidia driver generates code that does explicitly copy the whole array. Where do I move the issue for them to notice? Do you think creating a syntax-level solution is viable?

**Comment by pdaniell-nv** [comment]
Discussed in the OpenGL/ES meeting today. Some points/steps:
1) NVIDIA should investigate why they weren't able to optimize this case. Was it a bug, or is there a valid reason it can't optimize this case?
2) In many, perhaps most, cases the compiler should be able to recognize non-aliasing cases where it is okay to substitute a reference with a copy. If (1) is one of those cases, the "bug" could be fixed. If (1) is not one of those cases then:
3) To solve this completely there should be a new extension proposed to add reference keywords or syntax to GLSL so applications can be explicit about when reference should be used instead of a copy and compilers don't have to figure it out.

**Comment by pdaniell-nv** [comment]
@Raikiri what driver version were you using? Are you able to provide a stand-alone repro for this? Thanks.

**Comment by Raikiri** [comment]
@pdaniell-nv wow it's cool to know that the issue was escalated to nvidia level and things were actually happening around it. 

My driver version is 430.86. However, the pseudo-assembly output is from some other guy's machine that most likely has a different GPU with different version of the driver and apparently it has the same problem. Reproducible code is in the starting post of this issue, just render a big enough triangle with that shader, it has no inputs. If that's problematic, does not work, or you prefer a standalone executable anyway, let me know and I'll make one. Works in both OpenGL and Vulkan, but does NOT work in Shadertoy (probably because webgl is implemented over directx, from what i've heard).

**Comment by pdaniell-nv** [comment]
@Raikiri We put in an optimization for this case in the 436.52/435.27.00 driver you can find here: https://developer.nvidia.com/vulkan-driver. (I know it's a Vulkan beta driver, but sometimes it picks up OpenGL goodies too.)

Let me know if you see an improvement. Thanks.

**Comment by Raikiri** [comment]
@pdaniell-nv thanks guys for fixing that, but I still think it might be worth adding some sort of explicit reference syntax that would just fail to compile if inlining is impossible.

**Comment by pdaniell-nv** [comment]
@Raikiri does that mean the new driver fixed the performance issue you were having? Yes I agree it would be nice to have this explicit.

**Comment by Raikiri** [comment]
@pdaniell-nv hi. So I have tried 436.52:
![image](https://user-images.githubusercontent.com/1657728/66711919-6215ae00-edf1-11e9-9df8-59f2882c54ad.png)
And I have exactly the same performance as before on this code: https://github.com/KhronosGroup/GLSL/issues/84#issue-486287574
Which means no, it's not fixed.

**Comment by pdaniell-nv** [comment]
@Raikiri are you sure there was no improvement with 436.52? When I compare 436.39 and 436.52 locally I see that with the modified GLSL example (the one where CompareExchange() takes a parameter) I see the assembly generated by glslc no longer has all those MOVs.

**Comment by Raikiri** [comment]
Yes I'm pretty sure that I tested code from starting post of this thread after installing that driver, rebooting my machine and it did make more than 10x performance difference. I did not check what disassembly it gave me, just measured performance with an inout function argument vs global variable.

**Comment by greg-lunarg** [comment]
I think we have determined that glslang is doing just what it should given GLSL semantics. I am going to move this issue to GLSL by creating a new issue there with the same name, close this issue and point the new issue to this issue.

**Comment by greg-lunarg** [comment]
Sorry. Brain freeze. I thought this was a glslang issue. I am reopening this and closing #176.

**Comment by Raikiri** [comment]
> @Raikiri We put in an optimization for this case in the 436.52/435.27.00 driver you can find here: https://developer.nvidia.com/vulkan-driver. (I know it's a Vulkan beta driver, but sometimes it picks up OpenGL goodies too.)
> 
> Let me know if you see an improvement. Thanks.

5 years later, there's still no way to explicitly inline a function argument in GLSL syntax, and the driver optimizer broke yet again on the same usecase.

**Comment by jbarnoin** [comment]
> Reproduceable in 546.17, there's been a regression
> 
> Are there any workaround solutions that anyone knows of in the meantime that's better than lots of indices and hardcoding with globals?

Nothing fully general, but for many cases, working with Vulkan, I use the GL_EXT_buffer_reference GLSL extension (along with VK_KHR_buffer_device_address on the Vulkan side), which allows me to have pointers into specific array members within a buffer that I can pass in to function arguments and defererence.

There's more gymnastics involved than I like and some limitations, the main one being that you can't create a pointer to a local variable and pass that to a function. However if the data lives in a buffer, it's mostly workable if not entirely straightforward to setup.
