### ISSUE TITLE
Mismatch in the subgroup spec and subgroup tutorial about subgroupBroadcast

### ISSUE THREAD

**Issue by axinging** [KhronosGroup/GLSL#90]
Atfer comparing the Vulkan subgroup tutorial  and this subgroup spec, I found the explanation of subgroupBroadcast in Vulkan subgroup tutorial is contradictory to the explanation in the subgroup spec.

In the Vulkan subgroup tutorial (https://www.khronos.org/blog/vulkan-subgroup-tutorial), it said,

```
T subgroupBroadcast(T value, uint id) broadcasts the value whose gl_SubgroupInvocationID == id
to all other invocations (id must be a compile time constant). ”
```

So in this tutorial, subgroupBroadcast is a **WRITE** operation.

However, in the subgroup extension spec(https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_shader_subgroup.txt), it said,

```
The function subgroupBroadcast() returns the <value> from the invocation
whose <gl_SubgroupInvocationID> is equal to <id>.  <id> must be an integral
constant expression.  If the <id> is an inactive invocation or is
greater than or equal to <gl_SubgroupSize>, an undefined value is returned. 
```

Which means in the spec, it is a **READ** operations.

Did I miss anything?

[Edited to see the full quote, much of which was disappearing due to mark down.]

**Comment by johnkslang** [comment]
I don't see these statements as contradictory: The value both comes from somewhere and is delivered somewhere, and the statements simply have different focus on how they expressed that.  (Is one invocation broadcasting to the itself and the others, or are all invocations querying the one?  It's the same thing.)

Note the quoted text has also been updated to allow dynamically uniform `<id>` starting with SPIR-V 1.5.
