### ISSUE TITLE
No matching requirement for rayPayloadInNV

### ISSUE THREAD

**Issue by archimedus** [KhronosGroup/GLSL#93]
I suppose there is missing explicit requirement, that is though implied as for example @ewerness-nv mentions here https://github.com/KhronosGroup/glslang/issues/1638#issuecomment-454945406

> A closest hit shader with no functional rayPayloadInNV is allowed, but the trace call has to have one identified, so because of the **matching rules**, the closest hit shader has to have one, even if it's just an empty structure, so that's probably the best thing to warn on.

I can't find any traces of **matching rules** for `rayPayloadNV` / `rayPayloadInNV`

https://github.com/KhronosGroup/GLSL/blob/7af180fd19879171437d0665b6622d14d0d83164/extensions/nv/GLSL_NV_ray_tracing.txt#L332-L340

I suppose it should contain something similar to `callableDataInNV`

https://github.com/KhronosGroup/GLSL/blob/7af180fd19879171437d0665b6622d14d0d83164/extensions/nv/GLSL_NV_ray_tracing.txt#L358-L359

May be:

```
Type of this variable must match the type of rayPayloadNV as passed
by an upstream shader otherwise results are undefined.
```

**Comment by dgkoch** [comment]
Thanks for reporting. Proposed fix is in #96, just running it by the original authors yet.
